

services:
  db:
    image: mysql:8.0
    container_name: minidigi_db
    environment:
      MYSQL_DATABASE: mini_digi
      MYSQL_USER: minidigi_user
      MYSQL_PASSWORD: secure_password
      MYSQL_ROOT_PASSWORD: root_secure_password
    ports:
      - "3327:3327"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: minidigi_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: minidigi
      DB_USER: minidigi_user
      DB_PASSWORD: secure_password
      DB_HOST: db
      DB_PORT: 3327
    volumes:
      - .:/app

volumes:
  mysql_data: