# Generated by Django 5.2.15 on 2026-06-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
