# Generated by Django 6.0.6 on 2026-07-06 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_name_de_category_name_es_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_availab_388fee_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_purchas_503ea6_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='favorited_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='favorites_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchased_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
