# Generated by Django 6.0.6 on 2026-07-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_productvariant_is_default_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
