# Generated by Django 6.0.6 on 2026-08-02 14:41

import shop.models.variant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.variant.variant_image_path),
        ),
    ]
