# Generated by Django 6.0.6 on 2026-07-06 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orders_orde_created_0e92de_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_created_0e92de_idx',
        ),
    ]
