name: Backup to Drive
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM UTC

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      RCLONE_CONFIG_GDRIVE_TYPE: drive
      RCLONE_CONFIG_GDRIVE_SERVICE_ACCOUNT_FILE: /tmp/gdrive-sa.json
      RCLONE_CONFIG_GDRIVE_SCOPE: drive
      RCLONE_CONFIG_GDRIVE_ROOT_FOLDER_ID: "1ELKZwcEmgmW3_rEEIHgq140ehDVtapgh"

    steps:
      - uses: actions/checkout@v4

      - name: Set timestamp
        id: ts
        run: echo "stamp=$(TZ='Asia/Tehran' date +'%Y-%m-%d_%H-%M-%S')" >> "$GITHUB_OUTPUT"

      - name: Zip repo
        run: zip -r "backup_${{ steps.ts.outputs.stamp }}.zip" . -x ".git/*" -x ".github/*"

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Write SA Key
        run: echo '${{ secrets.GDRIVE_SA_KEY }}' > /tmp/gdrive-sa.json

      - name: Upload new backup
        run: rclone copy "backup_${{ steps.ts.outputs.stamp }}.zip" gdrive:MINI-DIGI/

      - name: Delete backups older than 25 days
        run: rclone delete gdrive:MINI-DIGI/ --min-age 25d
